---
# inventory/hosts.yml
# Replace IPs/hostnames with your actual server details

all:
  children:
    app_servers:
      hosts:
        prod-server-01:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/cicd_showcase_key
          env: production

        staging-server-01:
          ansible_host: 192.168.1.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/cicd_showcase_key
          env: staging

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
